env_files = [
    { path = "./.env.production", profile = "production" },
    { path = "./.env.local", profile = "development" },
]

[env]
PROJECT_NAME = "duck-stream"
ENV = ".env.local"
# DATA_DIR = "./database/data"
DOCKER_COMPOSE_LOCAL = "docker/docker-compose.yaml"
DOCKER_COMPOSE_LOCAL_SERVER = "docker/docker-compose.server.yaml"

[tasks.down]
command = "docker"
args = [
    "compose",
    "-p",
    "${PROJECT_NAME}",
    "down",
    "--rmi",
    "all",
    "--volumes",
    "--remove-orphans",
]

[tasks.clean]
dependencies = ["down"]
# command = "rm"
# args = ["-rf", "${DATA_DIR}"]

[tasks.up]
dependencies = ["down"]
command = "docker"
args = [
    "compose",
    "-p",
    "${PROJECT_NAME}",
    "-f",
    "${DOCKER_COMPOSE_LOCAL}",
    "-f",
    "${DOCKER_COMPOSE_LOCAL_SERVER}",
    "--env-file",
    "${ENV}",
    "up",
    "-d",
]
